### PR TITLE
Improve Dockerfile

### LINKED ISSUE #405: Make execution/testing with Docker more efficient
Testing with Docker requires a long delay after changing the code before the tweak can be tested. In other projects (e.g., [ipwb](https://github.com/oduwsdl/ipwb)), we have used waypoints/tags/othernomenclature to allow "sub-images" alraedy built to be reused:

e.g., `FROM       node`

This may speed up rebuilds and not require dependencies to be fetched.

### PR DESCRIPTION
**Pull request by ibnesayeed**
Enhances build cache utilization. Closes #405

### CODE REVIEW

**Comment by machawk1** [comment]
@ibnesayeed Tested and LGTM. I removed "authors", as there were a few other authors as well. Rather than including everyone, perhaps I'll use a contributors file. Having this information in the Dockerfile seems insufficient.

**Comment by ibnesayeed** [comment]
I copied labels from IPWB repo. The intention of authors was not necessarily contributors (which as per this repo is really just the two of us), but those who should be reached out in case of any Docker related issues/queries. It was in a sense a replacement of the (now deprecated) `MAINTAINER` Docker instruction. It could have better namespaced as `app.dockerfile.authors` though. That said, it is perfectly alright to not have it included, it is nothing but metadata and has no effect on the functionalities of the image.

**Comment by machawk1** [comment]
Thanks for the help in making this more efficient, @ibnesayeed!

**Comment by ibnesayeed** [comment]
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/ is a good place to learn about improving Docker images.

**Pull request merged**
